### PR TITLE
feat(app.js): implement infinite scroll

### PR DESCRIPTION
**Pull request by mehdirajani5**
Implement the feature.
Fix issue #1 

Kindly add `hacktoberfest` `hacktoberfest-accepted` label on it.

Thanks

### CODE REVIEW

**Comment by alok722** [comment]
@mehdirajani5 Have you tested it on your local? I am not able to verify it. I don't see the feature implemented.

**Comment by mehdirajani5** [comment]
@alok722  Can you share any video what is the output of the latest PR ?
API is not responding that's why you are feeling that the feature is not working.

**Comment by alok722** [comment]
> @alok722 Can you share any video what is the output of the latest PR ?
> API is not responding that's why you are feeling that the feature is not working.

see the screen record here, https://drive.google.com/file/d/1dUCkgFfcvzbI-BqfCQyOssXmhw6D17kp/view?usp=sharing
I don't see any API call after scrolling to bottom.

**Comment by mehdirajani5** [comment]
@alok722  
I had replaced the solution.  What I believe is the previous solution was not compatible with windows. While it was  working with Mac chrome
Well, Happy Coding :)

Do add the `hacktoberfest-accepted` label.

**Comment by mehdirajani5** [comment]
@alok722 
All good ?

**Comment by alok722** [comment]
@mehdirajani5  now, it works perfectly. thanks

**Pull request merged**
